version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      security-updates:
        applies-to: security-updates
        patterns:
          - '*'
      production-dependencies:
        applies-to: version-updates
        dependency-type: production
      development-dependencies:
        applies-to: version-updates
        dependency-type: development

  - package-ecosystem: nuget
    directory: /services/document-engine
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      nuget-updates:
        patterns:
          - '*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - '*'
